---
namespaceOverride: monitoring
prometheus:
  prometheusSpec:
    storageSpec:
     volumeClaimTemplate:
       spec:
        #  storageClassName: gluster
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 25Gi
grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-external
    hosts:
    - grafana.dev01.us-west-2.dev.ds.intacct.com.foo.foo.foo.foo.foo.foo
    tls:
    - hosts:
      - grafana.dev01.us-west-2.dev.ds.intacct.com # This should match a DNS name in the Certificate
      secretName: domain-wildcard # This should match the Certificate secretName
  additionalDataSources:
  - name: loki
    access: proxy
    basicAuth: false
    basicAuthPassword: pass
    basicAuthUser: daco
    editable: false
    jsonData:
        tlsSkipVerify: true
    orgId: 1
    type: loki
    url: http://loki-stack:3100
    version: 1

# Istio changes to not add the istio sidecar to the prometheus operator's addmission webhook patch
# https://github.com/prometheus-community/helm-charts/issues/479#issuecomment-752709725
prometheusOperator:
  admissionWebhooks:
    patch:
      podAnnotations:
        sidecar.istio.io/inject: "false"
