replicaCount: ${replica_count}

fullnameOverride: ${fullnameOverride}
namespace: ${namespace}

# containerSpecOptions:
#   securityContext:
#     runAsUser: 1000
#     runAsGroup: 1000

deployment:
  containers:
  - name: ${fullnameOverride}
    image:
      repository: ${docker_repository}
      tag: ${docker_tag}
      pullPolicy: Always

    env:
      base:
      - name: HTTP_PORT
        value: "8080"
      # - name: DB_HOST
      #   value: redis
      # - name: DB_PASS
      #   value: redis
      perEnv: []

    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
      servicePort: 8080

    resources:
      requests:
        memory: ${requests_memory}
