variable "region" {}
variable "profile" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "subnet_name" {}
variable "subnet_suffix" {}
variable "subnets" {}
variable "azs" {}
variable "default_inbound" {}
variable "custom_inbound" {}
variable "default_outbound" {}
variable "custom_outbound" {}
variable "create_subnet" {}